import {
  BarChart3,
  BookOpen,
  BrainCircuit,
  ClipboardList,
  Eye,
  FileText,
  Globe,
  GraduationCap,
  LayoutDashboard,
  LayoutTemplate,
  Layers,
  ListChecks,
  Presentation,
  Table2,
  Workflow,
  Wrench,
  type LucideIcon,
} from 'lucide-react'
import type { ServiceIcon } from '../data/services'

export const serviceIcons: Record<ServiceIcon, LucideIcon> = {
  systems: LayoutDashboard,
  data: BarChart3,
  ai: BrainCircuit,
  research: GraduationCap,
  education: BookOpen,
  products: LayoutTemplate,
  website: Globe,
  app: Layers,
  dashboard: LayoutDashboard,
  spreadsheet: Table2,
  automation: Workflow,
  reporting: ClipboardList,
  charts: BarChart3,
  ml: BrainCircuit,
  vision: Eye,
  datascience: BarChart3,
  support: GraduationCap,
  analysis: Table2,
  docs: FileText,
  tutoring: Presentation,
  walkthrough: Presentation,
  materials: BookOpen,
  tools: Wrench,
  tracker: ListChecks,
  template: LayoutTemplate,
}
